"""workspace saved searches lists tags

Revision ID: 1bf17dffeebb
Revises: c1d2e3f4a5b6
Create Date: 2026-07-14 09:48:13.927455

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1bf17dffeebb'
down_revision: str | None = 'c1d2e3f4a5b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_lists_name'), ['name'], unique=False)

    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('query_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_searches_name'), ['name'], unique=False)

    op.create_table('company_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['company_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'company_id', name='uq_list_company')
    )
    with op.batch_alter_table('company_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_list_items_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_list_items_list_id'), ['list_id'], unique=False)

    op.create_table('company_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'label', name='uq_company_label')
    )
    with op.batch_alter_table('company_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_tags_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_tags_label'), ['label'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_tags_label'))
        batch_op.drop_index(batch_op.f('ix_company_tags_company_id'))

    op.drop_table('company_tags')
    with op.batch_alter_table('company_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_list_items_list_id'))
        batch_op.drop_index(batch_op.f('ix_company_list_items_company_id'))

    op.drop_table('company_list_items')
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_searches_name'))

    op.drop_table('saved_searches')
    with op.batch_alter_table('company_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_lists_name'))

    op.drop_table('company_lists')
    # ### end Alembic commands ###
