"""marketing signals

Revision ID: 2a68ace07acd
Revises: 8c2f3f82ffdb
Create Date: 2026-07-13 14:21:13.955933

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2a68ace07acd'
down_revision: str | None = '8c2f3f82ffdb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketing_signals', schema=None) as batch_op:
        batch_op.create_index('ix_marketing_company_tool', ['company_id', 'tool_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_signals_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_signals_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketing_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_signals_company_id'))
        batch_op.drop_index(batch_op.f('ix_marketing_signals_category'))
        batch_op.drop_index('ix_marketing_company_tool')

    op.drop_table('marketing_signals')
    # ### end Alembic commands ###
