"""seo profiles

Revision ID: 5255d0c875a3
Revises: be279a2507ed
Create Date: 2026-07-13 07:59:47.645555

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5255d0c875a3'
down_revision: str | None = 'be279a2507ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('canonical', sa.String(length=2048), nullable=True),
    sa.Column('meta_robots', sa.String(length=256), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=False),
    sa.Column('h2_count', sa.Integer(), nullable=False),
    sa.Column('has_open_graph', sa.Boolean(), nullable=False),
    sa.Column('has_twitter_card', sa.Boolean(), nullable=False),
    sa.Column('has_structured_data', sa.Boolean(), nullable=False),
    sa.Column('has_ssl', sa.Boolean(), nullable=False),
    sa.Column('images_total', sa.Integer(), nullable=False),
    sa.Column('images_missing_alt', sa.Integer(), nullable=False),
    sa.Column('internal_links', sa.Integer(), nullable=False),
    sa.Column('external_links', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=1), nullable=False),
    sa.Column('cwv_lcp_ms', sa.Integer(), nullable=True),
    sa.Column('cwv_cls', sa.Float(), nullable=True),
    sa.Column('cwv_inp_ms', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_seo_profile_company')
    )
    with op.batch_alter_table('seo_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seo_profiles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_profiles_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_profiles_score'), ['score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seo_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_profiles_score'))
        batch_op.drop_index(batch_op.f('ix_seo_profiles_grade'))
        batch_op.drop_index(batch_op.f('ix_seo_profiles_company_id'))

    op.drop_table('seo_profiles')
    # ### end Alembic commands ###
