"""baseline: companies and domains

Revision ID: 8251184eae31
Revises: 
Create Date: 2026-07-13 05:35:27.179591

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8251184eae31'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('legal_name', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('size_bucket', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_size_bucket'), ['size_bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_status'), ['status'], unique=False)

    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('crawl_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname', name='uq_domains_hostname')
    )
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domains_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domains_crawl_status'), ['crawl_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domains_crawl_status'))
        batch_op.drop_index(batch_op.f('ix_domains_company_id'))

    op.drop_table('domains')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_status'))
        batch_op.drop_index(batch_op.f('ix_companies_size_bucket'))
        batch_op.drop_index(batch_op.f('ix_companies_industry'))
        batch_op.drop_index(batch_op.f('ix_companies_display_name'))

    op.drop_table('companies')
    # ### end Alembic commands ###
