"""performance indexes

Revision ID: 8c2f3f82ffdb
Revises: a4afe0ee0e7a
Create Date: 2026-07-13 13:27:38.253590

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8c2f3f82ffdb'
down_revision: str | None = 'a4afe0ee0e7a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_technologies', schema=None) as batch_op:
        batch_op.create_index('ix_comptech_tech_company', ['technology_id', 'company_id'], unique=False)

    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_crawljobs_status_created', ['status', 'created_at'], unique=False)

    with op.batch_alter_table('search_documents', schema=None) as batch_op:
        batch_op.create_index('ix_search_grade_score', ['seo_grade', 'seo_score'], unique=False)
        batch_op.create_index('ix_search_industry_score', ['industry', 'seo_score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_search_industry_score')
        batch_op.drop_index('ix_search_grade_score')

    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_crawljobs_status_created')

    with op.batch_alter_table('company_technologies', schema=None) as batch_op:
        batch_op.drop_index('ix_comptech_tech_company')

    # ### end Alembic commands ###
