"""search documents projection

Revision ID: a4afe0ee0e7a
Revises: 5255d0c875a3
Create Date: 2026-07-13 08:21:11.546639

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a4afe0ee0e7a'
down_revision: str | None = '5255d0c875a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_documents',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('primary_domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('size_bucket', sa.String(length=32), nullable=True),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('seo_grade', sa.String(length=1), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('technologies_text', sa.Text(), nullable=False),
    sa.Column('has_ssl', sa.Boolean(), nullable=False),
    sa.Column('has_contact_page', sa.Boolean(), nullable=False),
    sa.Column('has_careers_page', sa.Boolean(), nullable=False),
    sa.Column('has_blog', sa.Boolean(), nullable=False),
    sa.Column('has_privacy', sa.Boolean(), nullable=False),
    sa.Column('has_terms', sa.Boolean(), nullable=False),
    sa.Column('text_blob', sa.Text(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    with op.batch_alter_table('search_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_documents_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_documents_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_documents_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_documents_has_ssl'), ['has_ssl'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_documents_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_documents_primary_domain'), ['primary_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_documents_seo_grade'), ['seo_grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_documents_seo_score'), ['seo_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_documents_size_bucket'), ['size_bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_documents_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_documents_state'))
        batch_op.drop_index(batch_op.f('ix_search_documents_size_bucket'))
        batch_op.drop_index(batch_op.f('ix_search_documents_seo_score'))
        batch_op.drop_index(batch_op.f('ix_search_documents_seo_grade'))
        batch_op.drop_index(batch_op.f('ix_search_documents_primary_domain'))
        batch_op.drop_index(batch_op.f('ix_search_documents_industry'))
        batch_op.drop_index(batch_op.f('ix_search_documents_has_ssl'))
        batch_op.drop_index(batch_op.f('ix_search_documents_display_name'))
        batch_op.drop_index(batch_op.f('ix_search_documents_country'))
        batch_op.drop_index(batch_op.f('ix_search_documents_city'))

    op.drop_table('search_documents')
    # ### end Alembic commands ###
