"""technologies and page content

Revision ID: be279a2507ed
Revises: e424049a9121
Create Date: 2026-07-13 07:26:27.105198

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'be279a2507ed'
down_revision: str | None = 'e424049a9121'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tech_category_name')
    )
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['technology_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_technology_name')
    )
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technologies_category_id'), ['category_id'], unique=False)

    op.create_table('company_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'technology_id', name='uq_company_technology')
    )
    with op.batch_alter_table('company_technologies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_technologies_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_technologies_technology_id'), ['technology_id'], unique=False)

    with op.batch_alter_table('crawled_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('headers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawled_pages', schema=None) as batch_op:
        batch_op.drop_column('headers')
        batch_op.drop_column('html')

    with op.batch_alter_table('company_technologies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_technologies_technology_id'))
        batch_op.drop_index(batch_op.f('ix_company_technologies_company_id'))

    op.drop_table('company_technologies')
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technologies_category_id'))

    op.drop_table('technologies')
    op.drop_table('technology_categories')
    # ### end Alembic commands ###
