"""people and search roles

Revision ID: d667c3f195b6
Revises: e5a1c9f34b20
Create Date: 2026-07-15 03:35:44.656596

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd667c3f195b6'
down_revision: str | None = 'e5a1c9f34b20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('role_category', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_status', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_role_category'), ['role_category'], unique=False)

    # Server defaults backfill any existing rows; the model has no default, so
    # new rows are always written explicitly by the search adapter.
    with op.batch_alter_table('search_documents', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('roles', sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )
        batch_op.add_column(
            sa.Column('roles_text', sa.Text(), nullable=False, server_default='')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_documents', schema=None) as batch_op:
        batch_op.drop_column('roles_text')
        batch_op.drop_column('roles')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_role_category'))
        batch_op.drop_index(batch_op.f('ix_people_company_id'))

    op.drop_table('people')
    # ### end Alembic commands ###
