"""enrichment job queue

Revision ID: d81bdde11610
Revises: 1bf17dffeebb
Create Date: 2026-07-14 10:40:37.411222

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd81bdde11610'
down_revision: str | None = '1bf17dffeebb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_enrichjobs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_company_id'))
        batch_op.drop_index('ix_enrichjobs_status_created')

    op.drop_table('enrichment_jobs')
    # ### end Alembic commands ###
