"""crawl_jobs and crawled_pages

Revision ID: e424049a9121
Revises: 8251184eae31
Create Date: 2026-07-13 05:56:30.820966

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e424049a9121'
down_revision: str | None = '8251184eae31'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_jobs_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_jobs_status'), ['status'], unique=False)

    op.create_table('crawled_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_job_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('page_type', sa.String(length=32), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawled_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawled_pages_crawl_job_id'), ['crawl_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawled_pages_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawled_pages_page_type'), ['page_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawled_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawled_pages_page_type'))
        batch_op.drop_index(batch_op.f('ix_crawled_pages_domain_id'))
        batch_op.drop_index(batch_op.f('ix_crawled_pages_crawl_job_id'))

    op.drop_table('crawled_pages')
    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_crawl_jobs_domain_id'))

    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###
